# Generated by Django 4.2.14 on 2024-07-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='runtime',
            field=models.TextField(default=''),
        ),
    ]
